In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)

In [2]:
file = open("/content/car data - Copy.csv")
file.close()

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
car_data = pd.read_csv("/content/car data - Copy.csv")
print(car_data)

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol
1        sx4  2013           4.75           9.54       43000    Diesel
2       ciaz  2017           7.25           9.85        6900    Petrol
3    wagon r  2011           2.85           4.15        5200    Petrol
4      swift  2014           4.60           6.87       42450    Diesel
..       ...   ...            ...            ...         ...       ...
296     city  2016           9.50          11.60       33988    Diesel
297     brio  2015           4.00           5.90       60000    Petrol
298     city  2009           3.35          11.00       87934    Petrol
299     city  2017          11.50          12.50        9000    Diesel
300     brio  2016           5.30           5.90        5464    Petrol

    Seller_Type Transmission  Owner
0        Dealer       Manual      0
1        Dealer       Manual      0
2        Dealer       Manual      0
3        Dealer       Manual      0
4        Dealer       Manual      0
..          ...          ...    ...
296      Dealer       Manual      0
297      Dealer       Manual      0
298      Dealer       Manual      0
299      Dealer       Manual      0
300      Dealer       Manual      0

[301 rows x 9 columns]

In [5]:
car_data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [ ]:
car_data.shape

(299, 9)



```
# This is formatted as code
```

#preprocssing

#Null check

In [6]:
car_data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

#duplicate check

```
# This is formatted as code
```

In [7]:
car_data.duplicated().sum()

2

In [8]:
car_data.drop_duplicates(inplace=True)

In [10]:
car_data.shape

(299, 9)

In [9]:
car_data

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [11]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 299 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       299 non-null    object
 1   Year           299 non-null    int64
 2   Selling_Price  299 non-null    float64
 3   Present_Price  299 non-null    float64
 4   Kms_Driven     299 non-null    int64
 5   Fuel_Type      299 non-null    object
 6   Seller_Type    299 non-null    object
 7   Transmission   299 non-null    object
 8   Owner          299 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 23.4+ KB

#Data analysis

In [12]:
for col in car_data.columns:
  print('unique values of'+col)
  print(car_data[col].unique())
  print("==========\n")

unique values ofCar_Name
['ritz' 'sx4' 'ciaz' 'wagon r' 'swift' 'vitara brezza' 's cross'
 'alto 800' 'ertiga' 'dzire' 'alto k10' 'ignis' '800' 'baleno' 'omni'
 'fortuner' 'innova' 'corolla altis' 'etios cross' 'etios g' 'etios liva'
 'corolla' 'etios gd' 'camry' 'land cruiser' 'Royal Enfield Thunder 500'
 'UM Renegade Mojave' 'KTM RC200' 'Bajaj Dominar 400'
 'Royal Enfield Classic 350' 'KTM RC390' 'Hyosung GT250R'
 'Royal Enfield Thunder 350' 'KTM 390 Duke ' 'Mahindra Mojo XT300'
 'Bajaj Pulsar RS200' 'Royal Enfield Bullet 350'
 'Royal Enfield Classic 500' 'Bajaj Avenger 220' 'Bajaj Avenger 150'
 'Honda CB Hornet 160R' 'Yamaha FZ S V 2.0' 'Yamaha FZ 16'
 'TVS Apache RTR 160' 'Bajaj Pulsar 150' 'Honda CBR 150' 'Hero Extreme'
 'Bajaj Avenger 220 dtsi' 'Bajaj Avenger 150 street' 'Yamaha FZ  v 2.0'
 'Bajaj Pulsar  NS 200' 'Bajaj Pulsar 220 F' 'TVS Apache RTR 180'
 'Hero Passion X pro' 'Bajaj Pulsar NS 200' 'Yamaha Fazer '
 'Honda Activa 4G' 'TVS Sport ' 'Honda Dream Yuga '
 'Bajaj Avenger Street 220' 'Hero Splender iSmart' 'Activa 3g'
 'Hero Passion Pro' 'Honda CB Trigger' 'Yamaha FZ S '
 'Bajaj Pulsar 135 LS' 'Activa 4g' 'Honda CB Unicorn'
 'Hero Honda CBZ extreme' 'Honda Karizma' 'Honda Activa 125' 'TVS Jupyter'
 'Hero Honda Passion Pro' 'Hero Splender Plus' 'Honda CB Shine'
 'Bajaj Discover 100' 'Suzuki Access 125' 'TVS Wego' 'Honda CB twister'
 'Hero Glamour' 'Hero Super Splendor' 'Bajaj Discover 125' 'Hero Hunk'
 'Hero  Ignitor Disc' 'Hero  CBZ Xtreme' 'Bajaj  ct 100' 'i20' 'grand i10'
 'i10' 'eon' 'xcent' 'elantra' 'creta' 'verna' 'city' 'brio' 'amaze'
 'jazz']
==========

unique values ofYear
[2014 2013 2017 2011 2018 2015 2016 2009 2010 2012 2003 2008 2006 2005
 2004 2007]
==========

unique values ofSelling_Price
[ 3.35  4.75  7.25  2.85  4.6   9.25  6.75  6.5   8.75  7.45  6.85  7.5
  6.1   2.25  7.75  3.25  2.65  4.9   4.4   2.5   2.9   3.    4.15  6.
  1.95  3.1   2.35  4.95  5.5   2.95  4.65  0.35  5.85  2.55  1.25  1.05
  5.8  14.9  23.   18.   16.    2.75  3.6   4.5   4.1  19.99  6.95 18.75
 23.5  33.   19.75  4.35 14.25  3.95  1.5   5.25 14.5  14.73 12.5   3.49
 35.    5.9   3.45  3.8  11.25  3.51  4.   20.75 17.    7.05  9.65  1.75
  1.7   1.65  1.45  1.35  1.2   1.15  1.11  1.1   1.    0.95  0.9   0.75
  0.8   0.78  0.72  0.65  0.6   0.55  0.52  0.51  0.5   0.48  0.45  0.42
  0.4   0.38  0.31  0.3   0.27  0.25  0.2   0.18  0.17  0.16  0.15  0.12
  0.1   5.75  5.15  7.9   4.85 11.75  3.15  6.45  3.5   8.25  5.11  2.7
  6.15 11.45  3.9   9.1   4.8   2.    5.35  6.25  5.95  5.2   3.75 12.9
  5.    5.4   7.2  10.25  8.5   8.4   9.15  6.6   3.65  8.35  6.7   5.3
 10.9   8.65  9.7   2.1   8.99  7.4   5.65 10.11  6.4   8.55  9.5  11.5 ]
==========

unique values ofPresent_Price
[ 5.59   9.54   9.85   4.15   6.87   9.83   8.12   8.61   8.89   8.92
  3.6   10.38   9.94   7.71   7.21  10.79   5.09   7.98   3.95   5.71
  8.01   3.46   4.41   4.99   5.87   6.49   5.98   4.89   7.49   9.95
  8.06   7.74   7.2    2.28   3.76   7.87   3.98   7.15   2.69  12.04
  9.29  30.61  19.77  10.21  15.04   7.27  18.54   6.8   35.96  18.61
  7.7   36.23   6.95  23.15  20.45  13.74  20.91   6.76  12.48   8.93
 14.68  12.35  22.83  14.89   7.85  25.39  13.46  23.73  92.6    6.05
 16.09  13.7   22.78  18.64   1.9    1.82   1.78   1.6    1.47   2.37
  3.45   1.5    2.4    1.4    1.26   1.17   1.75   0.95   0.8    0.87
  0.84   0.82   0.81   0.74   1.2    0.787  0.99   0.94   0.826  0.55
  0.88   0.51   0.52   0.54   0.73   0.83   0.64   0.72   1.05   0.57
  0.48   0.58   0.47   0.75   0.65   0.32   6.79   5.7    4.6    4.43
  7.13   8.1   14.79  13.6    9.4    7.6    9.9    6.82   5.35   7.
  5.97   5.8    8.7   10.     7.5    8.4    5.9   14.    11.8    8.5
  7.9    6.4    6.1   13.09  11.6   11.    12.5  ]
==========

unique values ofKms_Driven
[ 27000  43000   6900   5200  42450   2071  18796  33429  20273  42367
   2135  51000  15000  26000  77427  41678  35500  41442  25000   2400
  50000  45280  56879  20000  55138  16200  44542  45000  51439  54200
  39000  49998  48767 127000  10079  62000  24524  46706  58000  45780
  64532  65000  25870  37000 104707  40000 135000  90000  70000  40534
  39485  41000  40001  40588  78000  47000   6000  11000  59000  88000
  12000  71000  56001  83000  36000  72000 135154  80000  89000  23000
  38000 197176 142000  56000  58242  75000  29000   8700  50024   3000
   1400   4000   1200   4100  21700  16500  18000   7000  35000  17000
  17500  33000  14000   5400   5700  46500  11500   1300   5000   3500
    500  11800  23500  16000  16600  32000  19000  24000  31000  13000
   8000   4300   8600  14500   1000  42000   5500   6700  13700  38600
  30000 213000  60000  21000   1900  22000  55000  49000 500000  53000
  92233  28200  53460  28282   3493  12479  34797   3435  21125  35775
  43535  22671  31604  20114  36100  12500  45078  38488  77632  61381
  36198  22517  24678  57000  52132  15001  12900   4492  15141  11849
  68000  60241  23709  32322  35866  34000  35934  56701  31427  48000
  54242  53675  49562  40324  36054  29223   5600  40023  16002  40026
  21200  19434  18828  69341  69562  27600  61203  30753  24800  21780
  40126  14465  50456  63000   9010   9800  15059  28569  44000  10980
  33019  60076  33988  87934   9000   5464]
==========

unique values ofFuel_Type
['Petrol' 'Diesel' 'CNG']
==========

unique values ofSeller_Type
['Dealer' 'Individual']
==========

unique values ofTransmission
['Manual' 'Automatic']
==========

unique values ofOwner
[0 1 3]
==========

In [13]:
def get_brand_name(car_name):
  car_name = car_name.split(' ')[0]
  return car_name.strip(' ')

In [90]:
def clean_data(value):
  value = value.split()
  value = value.strip()
  if value == '':
    value = 0
  return float (value)

In [91]:
get_brand_name('Royal Enfield Classic 350')

'Royal'

In [92]:
# Assuming the column is actually named 'Car_Name' based on the Global variables output.
car_data['car_name'] = car_data['Car_Name'].apply(get_brand_name)

In [93]:
car_data['car_name'].unique()

array(['ritz', 'sx4', 'ciaz', 'wagon', 'swift', 'vitara', 's', 'alto',
       'ertiga', 'dzire', 'ignis', '800', 'baleno', 'omni', 'fortuner',
       'innova', 'corolla', 'etios', 'camry', 'land', 'Royal', 'UM',
       'KTM', 'Bajaj', 'Hyosung', 'Mahindra', 'Honda', 'Yamaha', 'TVS',
       'Hero', 'Activa', 'Suzuki', 'i20', 'grand', 'i10', 'eon', 'xcent',
       'elantra', 'creta', 'verna', 'city', 'brio', 'amaze', 'jazz'],
      dtype=object)

In [94]:
for col in car_data.columns:
  print('unique values of'+col)
  print(car_data[col].unique())
  print("==========\n")

unique values ofindex
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298]
==========

unique values ofCar_Name
['ritz' 'sx4' 'ciaz' 'wagon r' 'swift' 'vitara brezza' 's cross'
 'alto 800' 'ertiga' 'dzire' 'alto k10' 'ignis' '800' 'baleno' 'omni'
 'fortuner' 'innova' 'corolla altis' 'etios cross' 'etios g' 'etios liva'
 'corolla' 'etios gd' 'camry' 'land cruiser' 'Royal Enfield Thunder 500'
 'UM Renegade Mojave' 'KTM RC200' 'Bajaj Dominar 400'
 'Royal Enfield Classic 350' 'KTM RC390' 'Hyosung GT250R'
 'Royal Enfield Thunder 350' 'KTM 390 Duke ' 'Mahindra Mojo XT300'
 'Bajaj Pulsar RS200' 'Royal Enfield Bullet 350'
 'Royal Enfield Classic 500' 'Bajaj Avenger 220' 'Bajaj Avenger 150'
 'Honda CB Hornet 160R' 'Yamaha FZ S V 2.0' 'Yamaha FZ 16'
 'TVS Apache RTR 160' 'Bajaj Pulsar 150' 'Honda CBR 150' 'Hero Extreme'
 'Bajaj Avenger 220 dtsi' 'Bajaj Avenger 150 street' 'Yamaha FZ  v 2.0'
 'Bajaj Pulsar  NS 200' 'Bajaj Pulsar 220 F' 'TVS Apache RTR 180'
 'Hero Passion X pro' 'Bajaj Pulsar NS 200' 'Yamaha Fazer '
 'Honda Activa 4G' 'TVS Sport ' 'Honda Dream Yuga '
 'Bajaj Avenger Street 220' 'Hero Splender iSmart' 'Activa 3g'
 'Hero Passion Pro' 'Honda CB Trigger' 'Yamaha FZ S '
 'Bajaj Pulsar 135 LS' 'Activa 4g' 'Honda CB Unicorn'
 'Hero Honda CBZ extreme' 'Honda Karizma' 'Honda Activa 125' 'TVS Jupyter'
 'Hero Honda Passion Pro' 'Hero Splender Plus' 'Honda CB Shine'
 'Bajaj Discover 100' 'Suzuki Access 125' 'TVS Wego' 'Honda CB twister'
 'Hero Glamour' 'Hero Super Splendor' 'Bajaj Discover 125' 'Hero Hunk'
 'Hero  Ignitor Disc' 'Hero  CBZ Xtreme' 'Bajaj  ct 100' 'i20' 'grand i10'
 'i10' 'eon' 'xcent' 'elantra' 'creta' 'verna' 'city' 'brio' 'amaze'
 'jazz']
==========

unique values ofYear
[2014 2013 2017 2011 2018 2015 2016 2009 2010 2012 2003 2008 2006 2005
 2004 2007]
==========

unique values ofSelling_Price
[ 3.35  4.75  7.25  2.85  4.6   9.25  6.75  6.5   8.75  7.45  6.85  7.5
  6.1   2.25  7.75  3.25  2.65  4.9   4.4   2.5   2.9   3.    4.15  6.
  1.95  3.1   2.35  4.95  5.5   2.95  4.65  0.35  5.85  2.55  1.25  1.05
  5.8  14.9  23.   18.   16.    2.75  3.6   4.5   4.1  19.99  6.95 18.75
 23.5  33.   19.75  4.35 14.25  3.95  1.5   5.25 14.5  14.73 12.5   3.49
 35.    5.9   3.45  3.8  11.25  3.51  4.   20.75 17.    7.05  9.65  1.75
  1.7   1.65  1.45  1.35  1.2   1.15  1.11  1.1   1.    0.95  0.9   0.75
  0.8   0.78  0.72  0.65  0.6   0.55  0.52  0.51  0.5   0.48  0.45  0.42
  0.4   0.38  0.31  0.3   0.27  0.25  0.2   0.18  0.17  0.16  0.15  0.12
  0.1   5.75  5.15  7.9   4.85 11.75  3.15  6.45  3.5   8.25  5.11  2.7
  6.15 11.45  3.9   9.1   4.8   2.    5.35  6.25  5.95  5.2   3.75 12.9
  5.    5.4   7.2  10.25  8.5   8.4   9.15  6.6   3.65  8.35  6.7   5.3
 10.9   8.65  9.7   2.1   8.99  7.4   5.65 10.11  6.4   8.55  9.5  11.5 ]
==========

unique values ofPresent_Price
[ 5.59   9.54   9.85   4.15   6.87   9.83   8.12   8.61   8.89   8.92
  3.6   10.38   9.94   7.71   7.21  10.79   5.09   7.98   3.95   5.71
  8.01   3.46   4.41   4.99   5.87   6.49   5.98   4.89   7.49   9.95
  8.06   7.74   7.2    2.28   3.76   7.87   3.98   7.15   2.69  12.04
  9.29  30.61  19.77  10.21  15.04   7.27  18.54   6.8   35.96  18.61
  7.7   36.23   6.95  23.15  20.45  13.74  20.91   6.76  12.48   8.93
 14.68  12.35  22.83  14.89   7.85  25.39  13.46  23.73  92.6    6.05
 16.09  13.7   22.78  18.64   1.9    1.82   1.78   1.6    1.47   2.37
  3.45   1.5    2.4    1.4    1.26   1.17   1.75   0.95   0.8    0.87
  0.84   0.82   0.81   0.74   1.2    0.787  0.99   0.94   0.826  0.55
  0.88   0.51   0.52   0.54   0.73   0.83   0.64   0.72   1.05   0.57
  0.48   0.58   0.47   0.75   0.65   0.32   6.79   5.7    4.6    4.43
  7.13   8.1   14.79  13.6    9.4    7.6    9.9    6.82   5.35   7.
  5.97   5.8    8.7   10.     7.5    8.4    5.9   14.    11.8    8.5
  7.9    6.4    6.1   13.09  11.6   11.    12.5  ]
==========

unique values ofKms_Driven
[ 27000  43000   6900   5200  42450   2071  18796  33429  20273  42367
   2135  51000  15000  26000  77427  41678  35500  41442  25000   2400
  50000  45280  56879  20000  55138  16200  44542  45000  51439  54200
  39000  49998  48767 127000  10079  62000  24524  46706  58000  45780
  64532  65000  25870  37000 104707  40000 135000  90000  70000  40534
  39485  41000  40001  40588  78000  47000   6000  11000  59000  88000
  12000  71000  56001  83000  36000  72000 135154  80000  89000  23000
  38000 197176 142000  56000  58242  75000  29000   8700  50024   3000
   1400   4000   1200   4100  21700  16500  18000   7000  35000  17000
  17500  33000  14000   5400   5700  46500  11500   1300   5000   3500
    500  11800  23500  16000  16600  32000  19000  24000  31000  13000
   8000   4300   8600  14500   1000  42000   5500   6700  13700  38600
  30000 213000  60000  21000   1900  22000  55000  49000 500000  53000
  92233  28200  53460  28282   3493  12479  34797   3435  21125  35775
  43535  22671  31604  20114  36100  12500  45078  38488  77632  61381
  36198  22517  24678  57000  52132  15001  12900   4492  15141  11849
  68000  60241  23709  32322  35866  34000  35934  56701  31427  48000
  54242  53675  49562  40324  36054  29223   5600  40023  16002  40026
  21200  19434  18828  69341  69562  27600  61203  30753  24800  21780
  40126  14465  50456  63000   9010   9800  15059  28569  44000  10980
  33019  60076  33988  87934   9000   5464]
==========

unique values ofFuel_Type
[1 2 3]
==========

unique values ofSeller_Type
[2 1]
==========

unique values ofTransmission
[1 2]
==========

unique values ofOwner
[0 1 3]
==========

unique values ofcar_name
['ritz' 'sx4' 'ciaz' 'wagon' 'swift' 'vitara' 's' 'alto' 'ertiga' 'dzire'
 'ignis' '800' 'baleno' 'omni' 'fortuner' 'innova' 'corolla' 'etios'
 'camry' 'land' 'Royal' 'UM' 'KTM' 'Bajaj' 'Hyosung' 'Mahindra' 'Honda'
 'Yamaha' 'TVS' 'Hero' 'Activa' 'Suzuki' 'i20' 'grand' 'i10' 'eon' 'xcent'
 'elantra' 'creta' 'verna' 'city' 'brio' 'amaze' 'jazz']
==========

In [95]:
car_data['car_name'].replace(['ritz', 'sx4', 'ciaz', 'wagon', 'swift', 'vitara', 's', 'alto',
       'ertiga', 'dzire', 'ignis', '800', 'baleno', 'omni', 'fortuner',
       'innova', 'corolla', 'etios', 'camry', 'land', 'Royal', 'UM',
       'KTM', 'Bajaj', 'Hyosung', 'Mahindra', 'Honda', 'Yamaha', 'TVS',
       'Hero', 'Activa', 'Suzuki', 'i20', 'grand', 'i10', 'eon', 'xcent',
       'elantra', 'creta', 'verna', 'city', 'brio', 'amaze', 'jazz'],
       [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44],
        inplace=True)
# The opening bracket for the list of replacement values and the opening bracket for the list of values to be replaced should be aligned with the start of the replace function call.

<ipython-input-95-d2a22064459a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_data['car_name'].replace(['ritz', 'sx4', 'ciaz', 'wagon', 'swift', 'vitara', 's', 'alto',
<ipython-input-95-d2a22064459a>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  car_data['car_name'].replace(['ritz', 'sx4', 'ciaz', 'wagon', 'swift', 'vitara', 's', 'alto',

In [96]:
car_data.reset_index(inplace=True)

In [97]:
car_data['Transmission'].unique()

array([1, 2])

In [98]:
car_data['Transmission'].replace(['Manual','Automatic'],[1,2],inplace=True)

<ipython-input-98-625cc7c1fef7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_data['Transmission'].replace(['Manual','Automatic'],[1,2],inplace=True)

In [99]:
car_data['Fuel_Type'].unique()

array([1, 2, 3])

In [100]:
car_data['Fuel_Type'].replace(['Petrol','Diesel','CNG'],[1,2,3],inplace=True)

<ipython-input-100-cca1e2eb6c4a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_data['Fuel_Type'].replace(['Petrol','Diesel','CNG'],[1,2,3],inplace=True)

In [101]:
car_data['Seller_Type'].unique()

array([2, 1])

In [102]:
car_data['Seller_Type'].replace(['Individual','Dealer'],[1,2],inplace=True)

<ipython-input-102-5e47f9b43070>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_data['Seller_Type'].replace(['Individual','Dealer'],[1,2],inplace=True)

In [103]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   level_0        299 non-null    int64
 1   index          299 non-null    int64
 2   Car_Name       299 non-null    object
 3   Year           299 non-null    int64
 4   Selling_Price  299 non-null    float64
 5   Present_Price  299 non-null    float64
 6   Kms_Driven     299 non-null    int64
 7   Fuel_Type      299 non-null    int64
 8   Seller_Type    299 non-null    int64
 9   Transmission   299 non-null    int64
 10  Owner          299 non-null    int64
 11  car_name       299 non-null    int64
dtypes: float64(2), int64(9), object(1)
memory usage: 28.2+ KB

In [115]:
car_data.reset_index(inplace=True)

In [116]:
car_data.drop(columns=['index'],inplace=True)

In [121]:
if '' in car_data.columns:
    car_data.drop(columns=[''], inplace=True)
else:
    print("No column with an empty name exists.")

No column with an empty name exists.

In [122]:
car_data

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,car_name
0,ritz,2014,3.35,5.59,27000,1,2,1,0,1
1,sx4,2013,4.75,9.54,43000,2,2,1,0,2
2,ciaz,2017,7.25,9.85,6900,1,2,1,0,3
3,wagon r,2011,2.85,4.15,5200,1,2,1,0,4
4,swift,2014,4.60,6.87,42450,2,2,1,0,5
...,...,...,...,...,...,...,...,...,...,...
294,city,2016,9.50,11.60,33988,2,2,1,0,41
295,brio,2015,4.00,5.90,60000,1,2,1,0,42
296,city,2009,3.35,11.00,87934,1,2,1,0,41
297,city,2017,11.50,12.50,9000,2,2,1,0,41
298,brio,2016,5.30,5.90,5464,1,2,1,0,42

# Model creation

In [123]:
input_data = car_data.drop(columns=['Selling_Price'])
output_data = car_data['Selling_Price']

In [124]:
x_train,x_shape,y_train,y_shape = train_test_split(input_data,output_data,test_size=0.2)

In [125]:
model = LinearRegression()

# Train model

In [126]:
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'Bajaj Avenger 220'

In [127]:
print(x_train.dtypes)

Car_Name          object
Year               int64
Present_Price    float64
Kms_Driven         int64
Fuel_Type          int64
Seller_Type        int64
Transmission       int64
Owner              int64
car_name           int64
dtype: object

In [137]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
x_train['car_name'] = label_encoder.fit_transform(x_train['car_name'])

# Create a mapping for known labels
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

# Map test data and assign a default for unseen labels
x_test['car_name'] = x_test['car_name'].map(label_mapping).fillna(-1).astype(int)

In [138]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Combine train and test sets for encoding
combined = pd.concat([x_train['car_name'], x_test['car_name']])
label_encoder.fit(combined)

# Apply encoding
x_train['car_name'] = label_encoder.transform(x_train['car_name'])
x_test['car_name'] = label_encoder.transform(x_test['car_name'])

In [140]:
model.fit(x_train,y_train)

LinearRegression()

In [141]:
predict=model.predict(x_test)

In [142]:
predict

array([ 7.33433591,  7.64225736,  1.83084148,  6.68781175, 10.67217223,
        4.27909696,  8.0457243 ,  1.9367336 ,  8.95630698, -1.23344303,
       10.26582192, -0.82281328,  1.00700529,  1.81705387,  3.47530879,
        4.83781508,  1.41017821,  2.15263683, 21.99359505,  1.009142  ,
        1.13780536,  1.40035192,  5.86763113, -0.3471844 ,  6.03347155,
        7.54379207,  8.11898015,  1.23587365,  5.10924348,  4.90811633,
        6.74787973,  4.33515465,  6.05019779,  2.5905931 ,  2.15714867,
        6.80889518,  1.41814674, -9.84269062,  1.41228457,  9.82385957,
        6.61594693,  9.01714189,  1.94479603,  2.93328397,  1.23613766,
       -2.17023566,  8.51292465,  4.08747808,  5.79230083, -0.71832196,
        1.00284012,  0.52553287,  5.30410707,  9.82642627,  6.83383255,
        5.75625924,  3.85551157,  2.86123243,  9.85887526,  9.04845729])

In [143]:
x_train.head(1)

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,car_name
130,2017,0.95,3500,1,1,1,0,23

In [152]:
input_data_model = pd.DataFrame({
    'Year': [2017],
    'Present_Price': [0.95],
    'Kms_Driven': [3500],
    'Fuel_Type': [1],
    'Seller_Type': [1],
    'Transmission': [1],
    'Owner': [0],
    'car_name': [23]
})

In [153]:
input_data_model

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,car_name
0,2017,0.95,3500,1,1,1,0,23

In [154]:
model.predict(input_data_model)

array([2.13718699])

In [156]:
import pickle as pk

In [157]:
pk.dump(model,open('model.pkl','wb'))